2021-04-21 16:03:14,106 INFO    MainThread:3731 [wandb_setup.py:_flush():69] setting env: {}
2021-04-21 16:03:14,106 INFO    MainThread:3731 [wandb_setup.py:_flush():69] setting login settings: {}
2021-04-21 16:03:14,106 INFO    MainThread:3731 [wandb_init.py:_log_setup():336] Logging user logs to /opt/ml/code/src/wandb/run-20210421_160314-lo065ooq/logs/debug.log
2021-04-21 16:03:14,106 INFO    MainThread:3731 [wandb_init.py:_log_setup():337] Logging internal logs to /opt/ml/code/src/wandb/run-20210421_160314-lo065ooq/logs/debug-internal.log
2021-04-21 16:03:14,106 INFO    MainThread:3731 [wandb_init.py:init():369] calling init triggers
2021-04-21 16:03:14,106 INFO    MainThread:3731 [wandb_init.py:init():376] wandb.init called with sweep_config: {}
config: {}
2021-04-21 16:03:14,106 INFO    MainThread:3731 [wandb_init.py:init():418] starting backend
2021-04-21 16:03:14,106 INFO    MainThread:3731 [backend.py:_multiprocessing_setup():71] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-04-21 16:03:14,118 INFO    MainThread:3731 [backend.py:ensure_launched():123] starting backend process...
2021-04-21 16:03:14,125 INFO    MainThread:3731 [backend.py:ensure_launched():128] started backend process with pid: 3756
2021-04-21 16:03:14,127 INFO    MainThread:3731 [wandb_init.py:init():423] backend started and connected
2021-04-21 16:03:14,128 INFO    MainThread:3731 [wandb_init.py:init():465] updated telemetry
2021-04-21 16:03:14,129 INFO    MainThread:3731 [wandb_init.py:init():484] communicating current version
2021-04-21 16:03:15,452 INFO    MainThread:3731 [wandb_init.py:init():489] got version response upgrade_message: "wandb version 0.10.27 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2021-04-21 16:03:15,452 INFO    MainThread:3731 [wandb_init.py:init():497] communicating run to backend with 30 second timeout
2021-04-21 16:03:15,677 INFO    MainThread:3731 [wandb_init.py:init():522] starting run threads in backend
2021-04-21 16:03:15,747 INFO    MainThread:3731 [wandb_run.py:_console_start():1524] atexit reg
2021-04-21 16:03:15,747 INFO    MainThread:3731 [wandb_run.py:_redirect():1371] redirect: SettingsConsole.REDIRECT
2021-04-21 16:03:15,748 INFO    MainThread:3731 [wandb_run.py:_redirect():1376] Redirecting console.
2021-04-21 16:03:15,758 INFO    MainThread:3731 [wandb_run.py:_redirect():1438] Redirects installed.
2021-04-21 16:03:15,758 INFO    MainThread:3731 [wandb_init.py:init():546] run started, returning control to user process
2021-04-21 16:04:28,519 INFO    MainThread:3731 [wandb_run.py:_atexit_cleanup():1494] got exitcode: 1
2021-04-21 16:04:28,521 INFO    MainThread:3731 [wandb_run.py:_restore():1466] restore
2021-04-21 16:04:30,732 INFO    MainThread:3731 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 527
  total_bytes: 527
}

2021-04-21 16:04:31,734 INFO    MainThread:3731 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 527
  total_bytes: 527
}

2021-04-21 16:04:32,130 INFO    MainThread:3731 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4338
  total_bytes: 4671
}

2021-04-21 16:04:32,233 INFO    MainThread:3731 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4338
  total_bytes: 4671
}

2021-04-21 16:04:32,335 INFO    MainThread:3731 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4671
  total_bytes: 4671
}

2021-04-21 16:04:32,437 INFO    MainThread:3731 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4671
  total_bytes: 4671
}

2021-04-21 16:04:32,539 INFO    MainThread:3731 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4671
  total_bytes: 4671
}

2021-04-21 16:04:32,641 INFO    MainThread:3731 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4671
  total_bytes: 4671
}

2021-04-21 16:04:32,743 INFO    MainThread:3731 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4671
  total_bytes: 4671
}

2021-04-21 16:04:32,845 INFO    MainThread:3731 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4671
  total_bytes: 4671
}

2021-04-21 16:04:32,947 INFO    MainThread:3731 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4671
  total_bytes: 4671
}

2021-04-21 16:04:33,049 INFO    MainThread:3731 [wandb_run.py:_wait_for_finish():1616] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4671
  total_bytes: 4671
}

2021-04-21 16:04:34,153 INFO    MainThread:3731 [wandb_run.py:_show_files():1838] logging synced files
