2021-04-22 07:04:56,173 INFO    MainThread:14536 [wandb_setup.py:_flush():69] setting env: {}
2021-04-22 07:04:56,174 INFO    MainThread:14536 [wandb_setup.py:_flush():69] setting login settings: {}
2021-04-22 07:04:56,174 INFO    MainThread:14536 [wandb_init.py:_log_setup():336] Logging user logs to /opt/ml/code/src/wandb/run-20210422_070456-1kexdnar/logs/debug.log
2021-04-22 07:04:56,174 INFO    MainThread:14536 [wandb_init.py:_log_setup():337] Logging internal logs to /opt/ml/code/src/wandb/run-20210422_070456-1kexdnar/logs/debug-internal.log
2021-04-22 07:04:56,174 INFO    MainThread:14536 [wandb_init.py:init():369] calling init triggers
2021-04-22 07:04:56,174 INFO    MainThread:14536 [wandb_init.py:init():376] wandb.init called with sweep_config: {}
config: {}
2021-04-22 07:04:56,174 INFO    MainThread:14536 [wandb_init.py:init():418] starting backend
2021-04-22 07:04:56,174 INFO    MainThread:14536 [backend.py:_multiprocessing_setup():71] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-04-22 07:04:56,185 INFO    MainThread:14536 [backend.py:ensure_launched():123] starting backend process...
2021-04-22 07:04:56,192 INFO    MainThread:14536 [backend.py:ensure_launched():128] started backend process with pid: 14561
2021-04-22 07:04:56,210 INFO    MainThread:14536 [wandb_init.py:init():423] backend started and connected
2021-04-22 07:04:56,211 INFO    MainThread:14536 [wandb_init.py:init():465] updated telemetry
2021-04-22 07:04:56,212 INFO    MainThread:14536 [wandb_init.py:init():484] communicating current version
2021-04-22 07:04:57,033 INFO    MainThread:14536 [wandb_init.py:init():489] got version response upgrade_message: "wandb version 0.10.27 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2021-04-22 07:04:57,033 INFO    MainThread:14536 [wandb_init.py:init():497] communicating run to backend with 30 second timeout
2021-04-22 07:04:57,260 INFO    MainThread:14536 [wandb_init.py:init():522] starting run threads in backend
2021-04-22 07:04:57,285 INFO    MainThread:14536 [wandb_run.py:_console_start():1524] atexit reg
2021-04-22 07:04:57,286 INFO    MainThread:14536 [wandb_run.py:_redirect():1371] redirect: SettingsConsole.REDIRECT
2021-04-22 07:04:57,286 INFO    MainThread:14536 [wandb_run.py:_redirect():1376] Redirecting console.
2021-04-22 07:04:57,288 INFO    MainThread:14536 [wandb_run.py:_redirect():1438] Redirects installed.
2021-04-22 07:04:57,288 INFO    MainThread:14536 [wandb_init.py:init():546] run started, returning control to user process
2021-04-22 07:05:28,543 INFO    MainThread:14536 [wandb_run.py:_atexit_cleanup():1494] got exitcode: 255
2021-04-22 07:05:28,552 INFO    MainThread:14536 [wandb_run.py:_restore():1466] restore
2021-04-22 07:05:30,769 INFO    MainThread:14536 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 569
  total_bytes: 569
}

2021-04-22 07:05:31,276 INFO    MainThread:14536 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 569
  total_bytes: 4674
}

2021-04-22 07:05:31,648 INFO    MainThread:14536 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4674
  total_bytes: 4674
}

2021-04-22 07:05:31,750 INFO    MainThread:14536 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4674
  total_bytes: 4674
}

2021-04-22 07:05:31,851 INFO    MainThread:14536 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4674
  total_bytes: 4674
}

2021-04-22 07:05:31,953 INFO    MainThread:14536 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4674
  total_bytes: 4674
}

2021-04-22 07:05:32,055 INFO    MainThread:14536 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4674
  total_bytes: 4674
}

2021-04-22 07:05:32,157 INFO    MainThread:14536 [wandb_run.py:_wait_for_finish():1616] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4674
  total_bytes: 4674
}

2021-04-22 07:05:33,247 INFO    MainThread:14536 [wandb_run.py:_show_files():1838] logging synced files
